name: onboarding_builder
description: A flexible Flutter package for building customizable onboarding flows with step-by-step guidance.
version: 0.1.0
homepage: https://github.com/username/onboarding_builder

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# flutter: