name: onboarding_builder
description: A highly customizable Flutter package for building beautiful onboarding flows with 7 unique styles including slide, card, full-screen, story, liquid wave, vertical scrolling, and floating elements.
version: 0.1.0
homepage: https://github.com/rahulshahDEV/onboardingBuilder
repository: https://github.com/rahulshahDEV/onboardingBuilder
issue_tracker: https://github.com/rahulshahDEV/onboardingBuilder/issues
documentation: https://github.com/rahulshahDEV/onboardingBuilder#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# flutter: